version: '3.8'

networks:
  shared-network:
    external: true

services:
  # postgres:
  #   image: postgres:15
  #   container_name: pybot_postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: pybot_db
  #     POSTGRES_USER: pybot_user
  #     POSTGRES_PASSWORD: pybot_pass
  #   ports:
  #     - "3363:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: pybot
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "src/main.py"]

volumes:
  postgres_data:
