version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: muslim571
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres; Port=5432; User Id=postgres; Password=muslim571; Database=testdb"
    depends_on:
      - postgres
    command: ["./run-migrations.sh"]

volumes:
  pgdata:
