version: '3.8'

services:
  app:
    build: .
    environment:
      ConnectionStrings__DefaultConnection: "Host=92.53.120.21; Port=5432; User Id=postgres; Password=muslim571; Database=testdb;"
    ports:
      - "5000:80" 